In [1]:
import pandas as pd
import json

In [19]:
# File paths
csv_file_path = '/home/yuna/github/CyclingVSPollution/yuna/project_data/london_with_borough_name.csv'
geojson_file_path = '/home/yuna/github/CyclingVSPollution/yuna/project_data/london_boroughs.geojson'
output_csv_file_path = 'london_boroughs_with_geometry.csv'
final_path = 'london_NO2_borough.csv'

In [3]:
# Load CSV data
csv_data = pd.read_csv(csv_file_path)

In [4]:
# Load GeoJSON data
with open(geojson_file_path, 'r') as f:
    geojson_data = json.load(f)

In [5]:
# Extract borough names and geometries from GeoJSON
geojson_boroughs = {
    feature['properties']['name']: feature['geometry']
    for feature in geojson_data['features']
}

In [6]:
# Add geometry to CSV data based on matching borough names
csv_data['geometry'] = csv_data['borough_name'].map(geojson_boroughs)

In [15]:
csv_final = csv_data[['borough_name', 'Average concentration roadside*', 'geometry']]
csv_final

,borough_name,Average concentration roadside*,geometry
0,City of London,32.2,"{'type': 'Polygon', 'coordinates': [[[-0.08527..."
1,Barking and Dagenham,26.6,"{'type': 'Polygon', 'coordinates': [[[0.188588..."
2,Barnet,NaN,"{'type': 'Polygon', 'coordinates': [[[-0.28515..."
3,Bexley,NaN,"{'type': 'Polygon', 'coordinates': [[[0.134178..."
4,Brent,22.5,"{'type': 'Polygon', 'coordinates': [[[-0.26548..."
5,Bromley,21.8,"{'type': 'Polygon', 'coordinates': [[[-0.00336..."
6,Camden,27.8,"{'type': 'Polygon', 'coordinates': [[[-0.14236..."
7,Croydon,NaN,"{'type': 'Polygon', 'coordinates': [[[0, 51.32..."
8,Ealing,26.7,"{'type': 'Polygon', 'coordinates': [[[-0.37892..."
9,Enfield,24.1,"{'type': 'Polygon', 'coordinates': [[[-0.01213..."
10,Hackney,24.4,"{'type': 'Polygon', 'coordinates': [[[-0.09569..."
11,Hammersmith and Fulham,NaN,"{'type': 'Polygon', 'coordinates': [[[-0.22868..."
12,Haringey,26.9,"{'type': 'Polygon', 'coordinates': [[[-0.09581..."
13,Harrow,24.6,"{'type': 'Polygon', 'coordinates': [[[-0.30455..."
14,Havering,NaN,"{'type': 'Polygon', 'coordinates': [[[0.159405..."
15,Hillingdon,26.7,"{'type': 'Polygon', 'coordinates': [[[-0.37695..."
16,Hounslow,22.6,"{'type': 'Polygon', 'coordinates': [[[-0.37814..."
17,Islington,28.9,"{'type': 'Polygon', 'coordinates': [[[-0.10459..."
18,Lambeth,27.2,"{'type': 'Polygon', 'coordinates': [[[-0.08896..."
19,Lewisham,21.3,"{'type': 'Polygon', 'coordinates': [[[0, 51.41..."
20,Merton,29.1,"{'type': 'Polygon', 'coordinates': [[[-0.14063..."
21,Newham,27.9,"{'type': 'Polygon', 'coordinates': [[[0.068432..."
22,Redbridge,28.6,"{'type': 'Polygon', 'coordinates': [[[0.094036..."
23,Richmond upon Thames,26.0,"{'type': 'Polygon', 'coordinates': [[[-0.37741..."
24,Southwark,24.3,"{'type': 'Polygon', 'coordinates': [[[-0.08021..."
25,Sutton,24.4,"{'type': 'Polygon', 'coordinates': [[[-0.21845..."
26,Tower Hamlets,25.6,"{'type': 'Polygon', 'coordinates': [[[0, 51.50..."
27,Waltham Forest,24.1,"{'type': 'Polygon', 'coordinates': [[[0.022200..."
28,Wandsworth,25.1,"{'type': 'Polygon', 'coordinates': [[[-0.13947..."
29,Westminster,29.8,"{'type': 'Polygon', 'coordinates': [[[-0.11164..."
30,Greenwich,26.7,"{'type': 'Polygon', 'coordinates': [[[0.074700..."
31,Kensington and Chelsea,26.9,"{'type': 'Polygon', 'coordinates': [[[-0.21635..."
32,Kingston upon Thames,20.7,"{'type': 'Polygon', 'coordinates': [[[-0.30068..."

In [16]:
# Save the updated CSV file with geometry column
csv_final.to_csv(final_path, index=False)

In [17]:
print(f"Updated data with geometry saved to {final_path}")

Updated data with geometry saved to london_borough_NO2_geometry.csv

In [18]:
csv_final.head()

,borough_name,Average concentration roadside*,geometry
0,City of London,32.2,"{'type': 'Polygon', 'coordinates': [[[-0.08527..."
1,Barking and Dagenham,26.6,"{'type': 'Polygon', 'coordinates': [[[0.188588..."
2,Barnet,NaN,"{'type': 'Polygon', 'coordinates': [[[-0.28515..."
3,Bexley,NaN,"{'type': 'Polygon', 'coordinates': [[[0.134178..."
4,Brent,22.5,"{'type': 'Polygon', 'coordinates': [[[-0.26548..."